-- TODO: Define Supabase schema if migrating away from Prisma in future.
-- Example table:
-- CREATE TABLE IF NOT EXISTS users (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   email text UNIQUE NOT NULL,
--   name text,
--   created_at timestamptz DEFAULT now()
-- );